import { Product, Category, BuyingGuide, Comparison, Author, Brand } from './types';

const pexelsImages = {
  smartphone: 'https://images.pexels.com/photos/69926/computer-smartphone-typography-smart-69926.jpeg?auto=compress&cs=tinysrgb&w=600',
  laptop: 'https://images.pexels.com/photos/20511/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
  earbuds: 'https://images.pexels.com/photos/3780695/pexels-photo-3780695.jpeg?auto=compress&cs=tinysrgb&w=600',
  smartwatch: 'https://images.pexels.com/photos/437036/pexels-photo-437036.jpeg?auto=compress&cs=tinysrgb&w=600',
  headphone: 'https://images.pexels.com/photos/3394662/pexels-photo-3394662.jpeg?auto=compress&cs=tinysrgb&w=600',
  tv: 'https://images.pexels.com/photos/400613/pexels-photo-400613.jpeg?auto=compress&cs=tinysrgb&w=600',
  camera: 'https://images.pexels.com/photos/1519050/pexels-photo-1519050.jpeg?auto=compress&cs=tinysrgb&w=600',
  appliance: 'https://images.pexels.com/photos/4228865/pexels-photo-4228865.jpeg?auto=compress&cs=tinysrgb&w=600',
  gaming: 'https://images.pexels.com/photos/461813/pexels-photo-461813.jpeg?auto=compress&cs=tinysrgb&w=600',
  tablet: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
  home: 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=600',
  fitness: 'https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg?auto=compress&cs=tinysrgb&w=600',
};

export const categories: Category[] = [
  {
    id: '1',
    slug: 'smartphones',
    name: 'Smartphones',
    description: 'Discover the best smartphones for every budget. Compare features, prices, and performance across top brands like Apple, Samsung, OnePlus, and more.',
    image: pexelsImages.smartphone,
    icon: 'Smartphone',
    productCount: 245,
    subcategories: ['Budget Phones', 'Flagship Phones', 'Gaming Phones', 'Camera Phones'],
  },
  {
    id: '2',
    slug: 'laptops',
    name: 'Laptops',
    description: 'Find the perfect laptop for work, gaming, or everyday use. Expert reviews and comparisons of the latest models.',
    image: pexelsImages.laptop,
    icon: 'Laptop',
    productCount: 189,
    subcategories: ['Gaming Laptops', 'Ultrabooks', 'Business Laptops', 'Budget Laptops'],
  },
  {
    id: '3',
    slug: 'earbuds',
    name: 'Earbuds & Headphones',
    description: 'Explore wireless earbuds and headphones with in-depth reviews on sound quality, comfort, and battery life.',
    image: pexelsImages.earbuds,
    icon: 'Headphones',
    productCount: 156,
    subcategories: ['Wireless Earbuds', 'Over-Ear Headphones', 'Gaming Headsets', 'Sports Earbuds'],
  },
  {
    id: '4',
    slug: 'smartwatches',
    name: 'Smartwatches',
    description: 'Compare smartwatches and fitness trackers. Find the best wearable for your lifestyle and budget.',
    image: pexelsImages.smartwatch,
    icon: 'Watch',
    productCount: 89,
    subcategories: ['Fitness Trackers', 'Smartwatches', 'Luxury Smartwatches'],
  },
  {
    id: '5',
    slug: 'home-appliances',
    name: 'Home Appliances',
    description: 'Expert recommendations for air conditioners, refrigerators, washing machines, and more.',
    image: pexelsImages.appliance,
    icon: 'Home',
    productCount: 134,
    subcategories: ['Air Conditioners', 'Refrigerators', 'Washing Machines', 'Microwaves'],
  },
  {
    id: '6',
    slug: 'cameras',
    name: 'Cameras',
    description: 'Find the perfect camera for photography or videography. Compare DSLRs, mirrorless, and action cameras.',
    image: pexelsImages.camera,
    icon: 'Camera',
    productCount: 78,
    subcategories: ['DSLR Cameras', 'Mirrorless Cameras', 'Action Cameras', 'Point & Shoot'],
  },
  {
    id: '7',
    slug: 'gaming',
    name: 'Gaming',
    description: 'Discover gaming consoles, accessories, and peripherals. Expert reviews for serious gamers.',
    image: pexelsImages.gaming,
    icon: 'Gamepad2',
    productCount: 112,
    subcategories: ['Consoles', 'Gaming Laptops', 'Controllers', 'Gaming Monitors'],
  },
  {
    id: '8',
    slug: 'tablets',
    name: 'Tablets',
    description: 'Compare tablets for work, entertainment, and creativity. Find the best slate for your needs.',
    image: pexelsImages.tablet,
    icon: 'Tablet',
    productCount: 67,
    subcategories: ['iPad', 'Android Tablets', 'Windows Tablets', 'Kids Tablets'],
  },
  {
    id: '9',
    slug: 'televisions',
    name: 'Televisions',
    description: 'Expert TV buying guides and reviews. Compare features, picture quality, and smart features.',
    image: pexelsImages.tv,
    icon: 'Tv',
    productCount: 92,
    subcategories: ['OLED TVs', 'QLED TVs', '4K TVs', 'Smart TVs'],
  },
  {
    id: '10',
    slug: 'fitness',
    name: 'Fitness Equipment',
    description: 'Find the best fitness equipment for home workouts. Expert reviews on treadmills, bikes, and more.',
    image: pexelsImages.fitness,
    icon: 'Dumbbell',
    productCount: 54,
    subcategories: ['Treadmills', 'Exercise Bikes', 'Weights', 'Yoga Equipment'],
  },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    brandSlug: 'apple',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    image: pexelsImages.smartphone,
    images: [pexelsImages.smartphone, pexelsImages.smartphone],
    rating: 4.8,
    reviewCount: 2847,
    currentPrice: 134900,
    originalPrice: 149900,
    discount: 10,
    availability: 'In Stock',
    highlights: ['A17 Pro Chip', 'Titanium Design', '5x Optical Zoom', 'USB-C'],
    pros: ['Exceptional camera system', 'Premium titanium build', 'A17 Pro delivers incredible performance', 'Long battery life'],
    cons: ['Very expensive', 'Slow charging speeds', 'No charger in the box'],
    features: {
      Display: '6.7" Super Retina XDR OLED',
      Processor: 'A17 Pro',
      RAM: '8GB',
      Storage: '256GB/512GB/1TB',
      'Main Camera': '48MP + 12MP + 12MP',
      Battery: '4422 mAh',
    },
    description: 'The iPhone 15 Pro Max represents the pinnacle of smartphone technology. With its titanium design, A17 Pro chip, and revolutionary camera system, it sets new standards for what a smartphone can do.',
    specifications: {
      Display: {
        Size: '6.7 inches',
        Type: 'Super Retina XDR OLED',
        Resolution: '2796 x 1290 pixels',
        'Refresh Rate': '120Hz ProMotion',
        'Peak Brightness': '2000 nits',
      },
      Camera: {
        Main: '48MP f/1.78',
        'Ultra Wide': '12MP f/2.2',
        Telephoto: '12MP f/2.8 (5x zoom)',
        'Front Camera': '12MP TrueDepth',
        'Video': '4K Cinematic Mode',
      },
      Performance: {
        Chip: 'A17 Pro',
        CPU: '6-core',
        GPU: '6-core',
        'Neural Engine': '16-core',
      },
      Battery: {
        Capacity: '4422 mAh',
        'Video Playback': '29 hours',
        'Fast Charging': '50% in 30 min',
        Charging: 'Lightning (iPhone 14), USB-C (iPhone 15)',
      },
    },
    faqs: [
      { question: 'Does it come with a charger?', answer: 'No, the iPhone 15 Pro Max does not come with a charger in the box. You need to purchase one separately or use an existing USB-C charger.' },
      { question: 'Is it water resistant?', answer: 'Yes, it has an IP68 rating which means it can withstand submersion in up to 6 meters of water for 30 minutes.' },
    ],
    affiliateUrl: 'https://amazon.in/dp/example',
    trending: true,
    editorsPick: true,
  },
  {
    id: '2',
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    brandSlug: 'samsung',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    image: pexelsImages.smartphone,
    images: [pexelsImages.smartphone],
    rating: 4.7,
    reviewCount: 2156,
    currentPrice: 129999,
    originalPrice: 144999,
    discount: 10,
    availability: 'In Stock',
    highlights: ['Snapdragon 8 Gen 3', '200MP Camera', 'S Pen Included', 'Titanium Frame'],
    pros: ['Best display on any phone', 'Incredible zoom camera', 'S Pen functionality', '7 years of updates'],
    cons: ['Expensive', 'Bulky and heavy', 'Charging could be faster'],
    features: {
      Display: '6.8" Dynamic AMOLED 2X',
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB',
      Storage: '256GB/512GB/1TB',
      'Main Camera': '200MP + 12MP + 50MP + 10MP',
      Battery: '5000 mAh',
    },
    description: 'The Galaxy S24 Ultra is Samsung\'s most powerful smartphone yet, featuring a stunning display, versatile camera system, and the built-in S Pen.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    trending: true,
    deal: { expiresIn: '2 days', savings: 15000 },
  },
  {
    id: '3',
    slug: 'macbook-pro-14-m3',
    name: 'MacBook Pro 14" M3 Pro',
    brand: 'Apple',
    brandSlug: 'apple',
    category: 'Laptops',
    categorySlug: 'laptops',
    image: pexelsImages.laptop,
    images: [pexelsImages.laptop],
    rating: 4.9,
    reviewCount: 1834,
    currentPrice: 169900,
    availability: 'In Stock',
    highlights: ['M3 Pro Chip', '18hr Battery Life', 'Liquid Retina XDR', 'Pro Audio System'],
    pros: ['Incredible M3 Pro performance', 'Outstanding battery life', 'Beautiful display', 'Premium build quality'],
    cons: ['Expensive', 'Limited ports', 'No touchscreen option'],
    features: {
      Display: '14.2" Liquid Retina XDR',
      Processor: 'Apple M3 Pro',
      RAM: '18GB/36GB',
      Storage: '512GB/1TB/2TB',
      Battery: '70Wh',
    },
    description: 'The MacBook Pro 14-inch with M3 Pro chip delivers unprecedented power for professional workflows.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    editorsPick: true,
  },
  {
    id: '4',
    slug: 'boat-airdotes-pro-4',
    name: 'boAt Airdopes 441',
    brand: 'boAt',
    brandSlug: 'boat',
    category: 'Earbuds & Headphones',
    categorySlug: 'earbuds',
    image: pexelsImages.earbuds,
    images: [pexelsImages.earbuds],
    rating: 4.2,
    reviewCount: 12453,
    currentPrice: 1299,
    originalPrice: 2990,
    discount: 57,
    availability: 'In Stock',
    highlights: ['30H Playtime', 'IWP Tech', 'Type-C Charging', 'IPX7'],
    pros: ['Excellent value for money', 'Good battery life', 'Compact design', 'Quick pairing'],
    cons: ['Average call quality', 'Bass-heavy sound', 'Mediocre ANC'],
    features: {
      Driver: '8mm',
      Battery: '30 hours with case',
      'Wireless Range': '10m',
      Bluetooth: '5.0',
    },
    description: 'The boAt Airdopes 441 offers incredible value with long battery life and solid audio performance.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    deal: { expiresIn: '1 day', savings: 1691 },
  },
  {
    id: '5',
    slug: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    brandSlug: 'apple',
    category: 'Smartwatches',
    categorySlug: 'smartwatches',
    image: pexelsImages.smartwatch,
    images: [pexelsImages.smartwatch],
    rating: 4.8,
    reviewCount: 987,
    currentPrice: 89900,
    availability: 'In Stock',
    highlights: ['S9 Chip', 'Double Tap', '36hr Battery', 'Precision Dual-Frequency GPS'],
    pros: ['Rugged titanium design', 'Incredible display outdoors', 'Best fitness tracking', 'Double tap gesture'],
    cons: ['Very expensive', 'iPhone only', 'Large size not for everyone'],
    features: {
      Display: '49mm Always-On Retina',
      Processor: 'S9 SiP',
      Battery: '36 hours',
      'Water Resistance': '100m',
    },
    description: 'The Apple Watch Ultra 2 is the most rugged and capable Apple Watch ever made.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    editorsPick: true,
  },
  {
    id: '6',
    slug: 'noise-colorfit-pro-4',
    name: 'Noise ColorFit Pro 4 Alpha',
    brand: 'Noise',
    brandSlug: 'noise',
    category: 'Smartwatches',
    categorySlug: 'smartwatches',
    image: pexelsImages.smartwatch,
    images: [pexelsImages.smartwatch],
    rating: 4.0,
    reviewCount: 5632,
    currentPrice: 2999,
    originalPrice: 5999,
    discount: 50,
    availability: 'In Stock',
    highlights: ['1.78" AMOLED', 'Bluetooth Calling', '100+ Watch Faces', 'IP68'],
    pros: ['Great display for the price', 'Bluetooth calling works well', 'Good fitness tracking', 'Affordable'],
    cons: ['Average battery life', 'Plastic build', 'Limited smart features'],
    features: {
      Display: '1.78" AMOLED',
      Battery: '7 days',
      'Water Resistance': 'IP68',
      'Connectivity': 'Bluetooth 5.2',
    },
    description: 'The Noise ColorFit Pro 4 Alpha offers excellent features at an unbeatable price point.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    deal: { expiresIn: '3 days', savings: 3000 },
  },
  {
    id: '7',
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    brandSlug: 'sony',
    category: 'Earbuds & Headphones',
    categorySlug: 'earbuds',
    image: pexelsImages.headphone,
    images: [pexelsImages.headphone],
    rating: 4.7,
    reviewCount: 3421,
    currentPrice: 29990,
    originalPrice: 34990,
    discount: 14,
    availability: 'In Stock',
    highlights: ['Industry-Leading ANC', '30hr Battery', 'Multipoint Connection', 'Speak-to-Chat'],
    pros: ['Best-in-class ANC', 'Excellent sound quality', 'Comfortable for long sessions', 'Great call quality'],
    cons: ['Expensive', 'Poor carrying case', 'No fold-flat design'],
    features: {
      Driver: '30mm',
      Battery: '30 hours',
      ANC: 'Adaptive',
      Weight: '250g',
    },
    description: 'The Sony WH-1000XM5 are the best noise-canceling headphones you can buy.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    editorsPick: true,
  },
  {
    id: '8',
    slug: 'lg-c3-oled-55',
    name: 'LG C3 OLED 55"',
    brand: 'LG',
    brandSlug: 'lg',
    category: 'Televisions',
    categorySlug: 'televisions',
    image: pexelsImages.tv,
    images: [pexelsImages.tv],
    rating: 4.9,
    reviewCount: 1876,
    currentPrice: 116990,
    originalPrice: 139990,
    discount: 16,
    availability: 'In Stock',
    highlights: ['OLED evo Panel', '4K 120Hz', 'Dolby Vision IQ', 'Game Optimizer'],
    pros: ['Incredible picture quality', 'Perfect blacks', 'Great for gaming', 'WebOS is smooth'],
    cons: ['Risk of burn-in', 'No HDR10+', 'Average sound'],
    features: {
      'Display Type': 'OLED evo',
      Size: '55 inches',
      Resolution: '4K (3840x2160)',
      'Refresh Rate': '120Hz native',
      HDR: 'Dolby Vision, HDR10, HLG',
    },
    description: 'The LG C3 OLED delivers stunning picture quality with perfect blacks and infinite contrast.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
  },
  {
    id: '9',
    slug: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    brandSlug: 'oneplus',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    image: pexelsImages.smartphone,
    images: [pexelsImages.smartphone],
    rating: 4.6,
    reviewCount: 1923,
    currentPrice: 64999,
    originalPrice: 69999,
    discount: 7,
    availability: 'In Stock',
    highlights: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W Charging', 'Rain Rescue'],
    pros: ['Fast charging', 'Clean OxygenOS', 'Great performance', 'Good cameras'],
    cons: ['No wireless charging', 'Curved screen not for everyone', 'IP65 only'],
    features: {
      Display: '6.82" LTPO AMOLED',
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '16GB',
      Storage: '256GB/512GB',
      Battery: '5400 mAh',
    },
    description: 'The OnePlus 12 offers flagship specs at a more accessible price point.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    trending: true,
  },
  {
    id: '10',
    slug: 'dell-xps-15',
    name: 'Dell XPS 15 (2024)',
    brand: 'Dell',
    brandSlug: 'dell',
    category: 'Laptops',
    categorySlug: 'laptops',
    image: pexelsImages.laptop,
    images: [pexelsImages.laptop],
    rating: 4.5,
    reviewCount: 1234,
    currentPrice: 149990,
    originalPrice: 169990,
    discount: 12,
    availability: 'Limited Stock',
    highlights: ['Intel Core Ultra 9', 'RTX 4060', '3.5K OLED', 'Premium Build'],
    pros: ['Stunning OLED display', 'Great performance', 'Premium build', 'Good keyboard'],
    cons: ['Runs hot under load', 'Webcam could be better', 'Limited ports'],
    features: {
      Display: '15.6" 3.5K OLED',
      Processor: 'Intel Core Ultra 9 185H',
      RAM: '32GB DDR5',
      Storage: '1TB SSD',
      GPU: 'RTX 4060',
    },
    description: 'The Dell XPS 15 continues to be one of the best Windows laptops for creative professionals.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
  },
  {
    id: '11',
    slug: 'samsung-galaxy-buds-pro-2',
    name: 'Samsung Galaxy Buds 2 Pro',
    brand: 'Samsung',
    brandSlug: 'samsung',
    category: 'Earbuds & Headphones',
    categorySlug: 'earbuds',
    image: pexelsImages.earbuds,
    images: [pexelsImages.earbuds],
    rating: 4.5,
    reviewCount: 2876,
    currentPrice: 12990,
    originalPrice: 19990,
    discount: 35,
    availability: 'In Stock',
    highlights: ['Hi-Fi Sound', '360 Audio', 'IPX7', '24hr Battery'],
    pros: ['Excellent sound quality', 'Good ANC', 'Seamless Samsung integration', 'Comfortable fit'],
    cons: ['Best with Samsung phones', 'Small case', 'Touch controls can be finicky'],
    features: {
      Driver: '11mm + 6.5mm dual',
      Battery: '8hr (29hr with case)',
      ANC: 'Yes',
      'Water Resistance': 'IPX7',
    },
    description: 'The Galaxy Buds 2 Pro offer excellent audio quality, especially for Samsung users.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
  },
  {
    id: '12',
    slug: 'sony-zv-e10-ii',
    name: 'Sony ZV-E10 II',
    brand: 'Sony',
    brandSlug: 'sony',
    category: 'Cameras',
    categorySlug: 'cameras',
    image: pexelsImages.camera,
    images: [pexelsImages.camera],
    rating: 4.6,
    reviewCount: 765,
    currentPrice: 79990,
    availability: 'In Stock',
    highlights: ['APS-C Sensor', '4K 60p', 'Product Review Mode', 'Directional Mic'],
    pros: ['Great for vlogging', 'Excellent autofocus', 'Interchangeable lenses', 'Good audio features'],
    cons: ['No in-body stabilization', 'Mediocre battery life', 'Menu system complex'],
    features: {
      Sensor: 'APS-C CMOS',
      Pixels: '26MP',
      Video: '4K 60fps',
      'ISO Range': '100-32000',
    },
    description: 'The Sony ZV-E10 II is the perfect camera for content creators and vloggers.',
    specifications: {},
    faqs: [],
    affiliateUrl: 'https://amazon.in/dp/example',
    editorsPick: true,
  },
];

export const authors: Author[] = [
  {
    id: '1',
    slug: 'priya-sharma',
    name: 'Priya Sharma',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    bio: 'Senior Tech Editor with 8 years of experience reviewing smartphones and wearables. Former tech journalist at leading publications.',
    expertise: ['Smartphones', 'Smartwatches', 'Wearables'],
    social: { twitter: 'priyasharma', linkedin: 'priyasharma' },
    articlesCount: 145,
    guides: [],
    comparisons: [],
  },
  {
    id: '2',
    slug: 'rahul-verma',
    name: 'Rahul Verma',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    bio: 'Audio enthusiast and reviewer specializing in headphones, earbuds, and sound systems. Audiophile for over 15 years.',
    expertise: ['Headphones', 'Earbuds', 'Audio', 'Home Theater'],
    social: { twitter: 'rahulverma', website: 'https://audioreviews.in' },
    articlesCount: 89,
    guides: [],
    comparisons: [],
  },
  {
    id: '3',
    slug: 'ananya-patel',
    name: 'Ananya Patel',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    bio: 'Laptop and PC specialist with a focus on productivity devices. Former IT consultant turned full-time reviewer.',
    expertise: ['Laptops', 'Desktops', 'Monitors', 'Peripherals'],
    social: { linkedin: 'ananyapatel' },
    articlesCount: 112,
    guides: [],
    comparisons: [],
  },
  {
    id: '4',
    slug: 'vikram-singh',
    name: 'Vikram Singh',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    bio: 'Home appliance expert helping families find the best products for their homes. Focus on energy efficiency and value.',
    expertise: ['Home Appliances', 'Air Conditioners', 'Kitchen Appliances'],
    social: { twitter: 'vikramsingh' },
    articlesCount: 78,
    guides: [],
    comparisons: [],
  },
];

export const buyingGuides: BuyingGuide[] = [
  {
    id: '1',
    slug: 'best-smartphones-under-30000',
    title: 'Best Smartphones Under Rs 30,000 in 2024',
    excerpt: 'Looking for a great smartphone without breaking the bank? Our comprehensive guide covers the top options under Rs 30,000.',
    content: 'Full article content here...',
    coverImage: pexelsImages.smartphone,
    author: authors[0],
    readingTime: 12,
    lastUpdated: '2024-01-15',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    tags: ['budget phones', 'smartphones', 'value for money'],
    productRecommendations: [
      { product: products[8], reason: 'Best overall performance', isTopPick: true },
      { product: products[3], reason: 'Best audio experience', isTopPick: false },
    ],
    tableOfContents: [
      { title: 'What to Look For', id: 'what-to-look-for' },
      { title: 'Our Top Picks', id: 'top-picks' },
      { title: 'Budget Options', id: 'budget-options' },
      { title: 'FAQs', id: 'faqs' },
    ],
  },
  {
    id: '2',
    slug: 'best-wireless-earbuds-2024',
    title: 'Best Wireless Earbuds for Every Budget in 2024',
    excerpt: 'From premium ANC to budget-friendly options, find the perfect wireless earbuds for your needs.',
    content: 'Full article content here...',
    coverImage: pexelsImages.earbuds,
    author: authors[1],
    readingTime: 15,
    lastUpdated: '2024-01-20',
    category: 'Earbuds & Headphones',
    categorySlug: 'earbuds',
    tags: ['earbuds', 'wireless', 'ANC', 'audio'],
    productRecommendations: [
      { product: products[6], reason: 'Best ANC', isTopPick: true },
      { product: products[3], reason: 'Best budget pick', isTopPick: true },
    ],
    tableOfContents: [
      { title: 'Understanding ANC', id: 'understanding-anc' },
      { title: 'Premium Options', id: 'premium' },
      { title: 'Mid-Range', id: 'mid-range' },
      { title: 'Budget Picks', id: 'budget' },
    ],
  },
  {
    id: '3',
    slug: 'best-laptops-for-students',
    title: 'Best Laptops for Students: Complete Guide',
    excerpt: 'Whether you need a laptop for coding, design, or general studies, we have the perfect recommendations.',
    content: 'Full article content here...',
    coverImage: pexelsImages.laptop,
    author: authors[2],
    readingTime: 18,
    lastUpdated: '2024-01-18',
    category: 'Laptops',
    categorySlug: 'laptops',
    tags: ['laptops', 'students', 'budget', 'productivity'],
    productRecommendations: [
      { product: products[2], reason: 'Best for creative students', isTopPick: true },
      { product: products[9], reason: 'Best Windows option', isTopPick: false },
    ],
    tableOfContents: [
      { title: 'What Students Need', id: 'student-needs' },
      { title: 'Best Overall', id: 'best-overall' },
      { title: 'Budget Options', id: 'budget' },
      { title: 'Premium Options', id: 'premium' },
    ],
  },
  {
    id: '4',
    slug: 'smartwatch-buying-guide',
    title: 'How to Choose the Right Smartwatch',
    excerpt: 'Everything you need to know about buying a smartwatch, from features to compatibility.',
    content: 'Full article content here...',
    coverImage: pexelsImages.smartwatch,
    author: authors[0],
    readingTime: 10,
    lastUpdated: '2024-01-22',
    category: 'Smartwatches',
    categorySlug: 'smartwatches',
    tags: ['smartwatches', 'fitness', 'wearables'],
    productRecommendations: [
      { product: products[4], reason: 'Best smartwatch overall', isTopPick: true },
      { product: products[5], reason: 'Best value', isTopPick: true },
    ],
    tableOfContents: [
      { title: 'Smartwatch vs Fitness Tracker', id: 'comparison' },
      { title: 'Key Features', id: 'features' },
      { title: 'Top Picks', id: 'top-picks' },
    ],
  },
  {
    id: '5',
    slug: 'best-tv-buying-guide',
    title: 'Complete TV Buying Guide: All You Need to Know',
    excerpt: 'Navigate the complex world of TV specifications and find the perfect television for your home.',
    content: 'Full article content here...',
    coverImage: pexelsImages.tv,
    author: authors[3],
    readingTime: 20,
    lastUpdated: '2024-01-10',
    category: 'Televisions',
    categorySlug: 'televisions',
    tags: ['TV', 'OLED', 'QLED', 'home entertainment'],
    productRecommendations: [
      { product: products[7], reason: 'Best OLED TV', isTopPick: true },
    ],
    tableOfContents: [
      { title: 'Understanding TV Technologies', id: 'technologies' },
      { title: 'Size Guide', id: 'size' },
      { title: 'HDR Explained', id: 'hdr' },
      { title: 'Top Recommendations', id: 'recommendations' },
    ],
  },
];

export const comparisons: Comparison[] = [
  {
    id: '1',
    slug: 'iphone-15-vs-samsung-s24',
    title: 'iPhone 15 Pro Max vs Samsung Galaxy S24 Ultra',
    excerpt: 'The ultimate flagship battle. Which premium smartphone should you buy?',
    productA: products[0],
    productB: products[1],
    winner: 'tie',
    summary: 'Both phones are excellent, but your choice depends on your ecosystem preference and priorities.',
    categories: [
      { name: 'Display', winner: 'B', details: 'Samsung\'s display is bigger and brighter', productA: 'Great OLED', productB: 'Superior brightness' },
      { name: 'Camera', winner: 'tie', details: 'Both offer excellent but different strengths', productA: 'Best for video', productB: 'Best zoom' },
      { name: 'Performance', winner: 'A', details: 'A17 Pro edges out in benchmarks', productA: 'Faster chip', productB: 'Very good performance' },
      { name: 'Battery', winner: 'B', details: 'S24 Ultra lasts longer', productA: '1 day use', productB: '1.5 days use' },
      { name: 'Value', winner: 'B', details: 'S24 Ultra offers more features', productA: 'Expensive', productB: 'Better value' },
    ],
    prosCons: {
      productA: { pros: ['Best video recording', 'Easier to use', 'Premium feel', 'Long support'], cons: ['Very expensive', 'Slower charging', 'No touchscreen'] },
      productB: { pros: ['S Pen included', 'Better zoom camera', 'Longer battery', 'More features'], cons: ['Bulky', 'One UI complexity', 'Expensive'] },
    },
    verdict: 'If you\'re already in the Apple ecosystem, the iPhone 15 Pro Max is the natural choice. If you want the most versatile smartphone with S Pen support, go with the S24 Ultra.',
  },
  {
    id: '2',
    slug: 'boat-vs-noise-earbuds',
    title: 'boAt vs Noise: Which Earbuds Brand is Better?',
    excerpt: 'Two of India\'s most popular earbuds brands compared. Find out which offers better value.',
    productA: products[3],
    productB: products[10],
    winner: 'tie',
    summary: 'Both offer great value, but boAt wins on battery while Noise offers better sound.',
    categories: [
      { name: 'Sound Quality', winner: 'B', details: 'Noise has better audio tuning', productA: 'Bass-heavy', productB: 'Balanced' },
      { name: 'Battery Life', winner: 'A', details: 'boAt offers longer playback', productA: '30 hours', productB: '8 hours buds' },
      { name: 'Build Quality', winner: 'tie', details: 'Both are plastic but well made', productA: 'Good', productB: 'Good' },
      { name: 'Value', winner: 'A', details: 'boAt offers more for less', productA: 'Better deal', productB: 'Good value' },
    ],
    prosCons: {
      productA: { pros: ['Great battery', 'Very affordable', 'Good bass', 'Wide range'], cons: ['Average call quality', 'Bass-heavy', 'ANC limited'] },
      productB: { pros: ['Better sound', 'Good ANC', 'Premium feel', 'Samsung integration'], cons: ['Expensive', 'Battery average', 'Limited to Samsung users'] },
    },
    verdict: 'For pure value, boAt is the winner. For better audio quality and features, Noise is worth the premium.',
  },
  {
    id: '3',
    slug: 'macbook-vs-dell-xps',
    title: 'MacBook Pro 14" vs Dell XPS 15: Which Pro Laptop Wins?',
    excerpt: 'The ultimate battle between the best premium laptops from Apple and Dell.',
    productA: products[2],
    productB: products[9],
    winner: 'A',
    summary: 'MacBook Pro wins on battery and performance, but XPS 15 offers more versatility.',
    categories: [],
    prosCons: {
      productA: { pros: ['Incredible M3 Pro', 'Best battery', 'Premium build', 'Excellent speakers'], cons: ['Expensive', 'Limited ports', 'No touchscreen'] },
      productB: { pros: ['Stunning OLED', 'Windows flexibility', 'RTX GPU', 'Touch option'], cons: ['Runs hot', 'Battery average', 'Webcam average'] },
    },
    verdict: 'Creative professionals should choose MacBook Pro. Windows users who need GPU power should go XPS.',
  },
];

export const brands: Brand[] = [
  { id: '1', slug: 'apple', name: 'Apple', logo: '/brands/apple.png', description: 'Premium tech products', productCount: 45, rating: 4.8 },
  { id: '2', slug: 'samsung', name: 'Samsung', logo: '/brands/samsung.png', description: 'Innovation leader', productCount: 89, rating: 4.6 },
  { id: '3', slug: 'sony', name: 'Sony', logo: '/brands/sony.png', description: 'Audio excellence', productCount: 34, rating: 4.7 },
  { id: '4', slug: 'boat', name: 'boAt', logo: '/brands/boat.png', description: 'Affordable audio', productCount: 67, rating: 4.2 },
  { id: '5', slug: 'noise', name: 'Noise', logo: '/brands/noise.png', description: 'Wearable pioneer', productCount: 52, rating: 4.1 },
  { id: '6', slug: 'oneplus', name: 'OnePlus', logo: '/brands/oneplus.png', description: 'Flagship killer', productCount: 28, rating: 4.5 },
  { id: '7', slug: 'dell', name: 'Dell', logo: '/brands/dell.png', description: 'Business laptops', productCount: 43, rating: 4.4 },
  { id: '8', slug: 'lg', name: 'LG', logo: '/brands/lg.png', description: 'Home appliances', productCount: 56, rating: 4.5 },
];

export const getTrendingProducts = () => products.filter(p => p.trending);
export const getEditorsPicks = () => products.filter(p => p.editorsPick);
export const getDeals = () => products.filter(p => p.deal);
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getCategoryBySlug = (slug: string) => categories.find(c => c.slug === slug);
export const getGuideBySlug = (slug: string) => buyingGuides.find(g => g.slug === slug);
export const getComparisonBySlug = (slug: string) => comparisons.find(c => c.slug === slug);
export const getAuthorBySlug = (slug: string) => authors.find(a => a.slug === slug);
export const getProductsByCategory = (slug: string) => products.filter(p => p.categorySlug === slug);
export const getGuidesByCategory = (slug: string) => buyingGuides.filter(g => g.categorySlug === slug);
